todo: true
title: TODO
url: /projects/todo
desc: TODO
role: Programmer
begin_year: 0000
end_year: 0000
links:
  languages:
    - title: TODO
      url: /languages/todo

  db:
    - title: TODO
      url: /db/todo

  os:
    - title: TODO
      url: /os/todo
