exclude: [LICENSE, README.md, Gemfile, Gemfile.lock, Gruntfile.coffee, package.json, package-lock.json, Rakefile, node_modules, tsconfig.json]
markdown: kramdown
permalink: pretty

defaults:
- scope:
    path: ""
  values:
      layout: default

- scope:
    path: "db"
    type: "pages"
  values:
    layout: "db"

- scope:
    path: "jobs"
    type: "pages"
  values:
    layout: "job"

- scope:
    path: "languages"
    type: "pages"
  values:
    layout: "language"

- scope:
    path: "os"
    type: "pages"
  values:
    layout: "os"

- scope:
    path: "projects"
    type: "pages"
  values:
    layout: "project"

- scope:
    path: "schools"
    type: "pages"
  values:
    layout: "school"

- scope:
    path: "tools"
    type: "pages"
  values:
    layout: "tool"
