todo: true
title: TrainBuilder
url: /projects/train-builder
desc: TODO
role: Technical Lead
begin_year: 2007
end_year: 2007
links:
  languages:
    - title: C#
      url: /languages/cs

  db:
    - title: SQL Server
      url: /db/sql-server

  os:
    - title: TODO
      url: /os/todo
