title: TrainBuilder
desc: Windows Presentation Framework (WPF) application used by the Alaska Railroad to plan and schedule structure of their trains.
role: Developer
begin_year: 2007
end_year: 2007
_links:
  languages:
    - title: C#
      href: /languages/cs/

    - title: SQL
      href: /languages/sql/

  db:
    - title: SQL Server
      href: /db/sql-server/
