todo: true
title: TrainBuilder
url: /projects/train-builder
desc: TODO
role: Developer
begin_year: 2007
end_year: 2007
links:
  languages:
    - title: C#
      url: /languages/cs

    - title: SQL
      url: /languages/sql

  db:
    - title: SQL Server
      url: /db/sql-server

  os:
    - title: Windows
      url: /os/windows
